server:
  port: 8082

aws:
  sqs:
    endpoint: https://sqs.us-east-1.amazonaws.com
    queue:
      pagamento:
        name: tech_challenge_pagamento
      pedido:
        name: tech_challenge_pedido
        endpoint: https://sqs.us-east-1.amazonaws.com/358266770835/tech_challenge_producao



  dynamodb:
    endpoint: https://dynamodb.us-east-1.amazonaws.com

  region: us-east-1
  accessKey: ASIAVG2S5CWJ2DP2YUL7
  secretKey: hmTcqGcJwH3yFrYL7GN2uSBOMyRCTHQd8y/4NGJn
  sessionToken: IQoJb3JpZ2luX2VjEKr//////////wEaCXVzLXdlc3QtMiJHMEUCIFAkEdpW2dUTRNv2zadEW1fw3Q6qEHXnrmsrUCoH46LXAiEAurxEm4Q5jCMgjUj+t+r37brQCl72PD2NAJwfOPj3VrUqrQIIIxABGgwzNTgyNjY3NzA4MzUiDJCqUHKoJ0q27exQZCqKAsleZlxDSIIUiODDpV2uDJcgzxGCteDC9n1nm0qkVUfRJ1QzaPP4wRJ0E57pPoiXBhygN9ditmrr0tEjd8fOjGemXBcnVEMU7eLtYAnYnuYGkcGYHI6Wiezu8lUXl/RF634VyYcqwR0KPXkMz/m7lwdu3k/TXsvHnwh6UlWvOjbMouhkhx10U5xRD8NiHacV45Ri8wzWwF1P0tod6qlpFYgBjlJ3bBG0xPad/xsaE0awjqc1leLWMqIu3dcDVm+OJzXoWC8ra6xOKVqcCzYrTxgZfizXWRGShAmiFzzjODJCglw5nJ2GIfigHWomkC0SBaUF5JwS9xR8j3u0/R6QajLJF6O7qFRRv1ijMJ3iqrIGOp0Bi0YJzr0VjbHlZg1Fsq1ayGMmtwCGGGEiY5gPDiX3hRoyoCRhc5o99mG7i/o4Iu6E0XpNHSArNzwDWqCu+JTd/XDp4wseUPUmb9FIipoD3btlguW+HdLW0LAfNNflJzNmVLCbU1men8j/U8z4iguOKOuAEoEPTbZ+5uVWFAcMESjahRxekgD/OkG7NKeDe5thjz5xpUmXLRrEK2LNpA==
