aws:
  sqs:
    queue:
      pagamento:
        endpoint: http://localhost:4566/000000000000/tech_challenge_pagamento
      pedido:
        endpoint: http://localhost:4566/000000000000/tech_challenge_pedido
